import { ClientEvents } from "discord.js";

export const events_params: {
  [data in keyof ClientEvents]: string;
} = {
  channelCreate: "channel",
  channelDelete: "channel",
  channelPinsUpdate: "channel, date",
  channelUpdate: "oldChannel, newChannel",
  debug: "message",
  warn: "message",
  emojiCreate: "emoji",
  emojiDelete: "emoji",
  emojiUpdate: "oldEmoji, newEmoji",
  error: "error",
  guildBanAdd: "guild, user",
  guildBanRemove: "guild, user",
  guildCreate: "guild",
  guildDelete: "guild",
  guildUnavailable: "guild",
  guildIntegrationsUpdate: "guild",
  guildMemberAdd: "member",
  guildMemberAvailable: "member",
  guildMemberRemove: "member",
  guildMembersChunk: "members, guild, data",
  guildMemberSpeaking: "member, speaking",
  guildMemberUpdate: "oldMember, newMember",
  guildUpdate: "oldGuild, newGuild",
  inviteCreate: "invite",
  inviteDelete: "invite",
  message: "message",
  messageDelete: "message",
  messageReactionRemoveAll: "message",
  messageReactionRemoveEmoji: "reaction",
  messageDeleteBulk: "messages",
  messageReactionAdd: "message, user",
  messageReactionRemove: "reaction, user",
  messageUpdate: "oldMessage, newMessage",
  presenceUpdate: "oldPresence, newPresence",
  rateLimit: "rateLimitData",
  disconnect: "args_0, number",
  ready: "",
  invalidated: "",
  roleCreate: "role",
  roleDelete: "role",
  roleUpdate: "oldRole, newRole",
  typingStart: "channel, user",
  userUpdate: "oldUser, newUser",
  voiceStateUpdate: "oldState, newState",
  webhookUpdate: "channel",
  shardDisconnect: "closeEvent, shardID",
  shardError: "error, shardID",
  shardReady: "shardID, unavailableGuilds",
  shardReconnecting: "shardID",
  shardResume: "shardID, replayedEvents",
};
